# Generated by Django 4.2.1 on 2023-10-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_waybill_receipt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date',
            new_name='invoice_date',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='signature',
            field=models.ImageField(blank=True, upload_to='signatures/'),
        ),
    ]
