# Generated by Django 4.2.1 on 2023-10-18 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice_waybill_receipt', '0004_enduser_delete_document_alter_invoice_delivered_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivered_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EndUser',
        ),
    ]
