# Generated by Django 4.2.1 on 2023-10-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_remove_userprofile_city_remove_userprofile_country_and_more'),
        ('invoice_waybill_receipt', '0005_alter_invoice_delivered_to_delete_enduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivered_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile'),
        ),
    ]
