# Generated by Django 4.2.1 on 2023-10-19 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_remove_userprofile_city_remove_userprofile_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice_waybill_receipt', '0007_alter_invoice_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivered_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sent_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
