# Generated by Django 4.2.1 on 2023-09-04 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessprofile', '0002_businessprofile_logo'),
        ('cluster', '0002_cluster_commodity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Size in Hectares')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessprofile.businessprofile')),
                ('cluster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cluster.cluster')),
            ],
        ),
    ]
