# Generated by Django 4.2.1 on 2023-09-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='cluster',
        ),
    ]
