# Generated by Django 4.2.1 on 2023-09-04 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_cluster_commodity'),
        ('farm', '0002_remove_farm_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cluster.cluster'),
        ),
    ]
