# Generated by Django 4.2.1 on 2023-09-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_rename_commodityname_commodity_commodity_name'),
        ('farm', '0005_farm_farm_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='commodity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms', to='commodity.commodity'),
        ),
    ]
