# Generated by Django 4.2.1 on 2023-09-07 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_alter_address_osm_checked'),
        ('farm', '0010_alter_farm_farm_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
