# Generated by Django 4.2.1 on 2023-09-08 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_rename_commodityname_commodity_commodity_name'),
        ('farm', '0011_alter_farm_farm_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='commodity.commodity'),
        ),
    ]
