# Generated by Django 4.2.1 on 2023-08-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_address_created_at_address_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_detail",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Apartment, Suite, Unit, Box number, etc.",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="administrative_area",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="State, Province or Region name",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="locality",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="City or Town name"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Postal code"
            ),
        ),
    ]
