# Generated by Django 4.2.1 on 2023-08-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0004_alter_address_address_detail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="osm_checked",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether or not the location was checked by OSM.",
                verbose_name="Checked by Open Street Map API",
            ),
        ),
    ]
