# Generated by Django 4.2.1 on 2023-05-31 17:00

from django.db import migrations
from django.contrib.auth.models import Group, User

def create_initial_data(apps, schema_editor):
    group_names = [
        "farmer",
        "buyer",
        "investor",
        "input",
        "service",
        "processor"
    ]
    groups = []
    for name in group_names:
        groups.append(Group.objects.create(name=name))

    User.objects.create_superuser(
        username = "admin",
        email = "superadmin@fake.com",
        password = "admin123",
    ).groups.set(groups)

    

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
