# Generated by Django 4.2.1 on 2023-11-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_message_file_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='multimedia_url_expiration',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
