# Generated by Django 4.2.1 on 2023-06-14 21:22

import cubeseed.userprofile.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_userprofile_created_at_userprofile_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="picture",
        ),
        migrations.CreateModel(
            name="UserProfilePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        upload_to=cubeseed.userprofile.models.upload_user_profile_image,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "userProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userprofile.userprofile",
                    ),
                ),
            ],
        ),
    ]
