# Generated by Django 4.2.1 on 2023-06-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0003_remove_userprofile_picture_userprofilephoto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofilephoto",
            old_name="userProfile",
            new_name="user_profile",
        ),
    ]
