# Generated by Django 4.2.1 on 2023-07-29 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_farmerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='reviewed_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_farmers', to='userprofile.userprofile'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='review_status',
            field=models.CharField(choices=[('P', 'PENDING'), ('R', 'REJECTED'), ('A', 'APPROVED')], default='P', max_length=1),
        ),
    ]
