# Generated by Django 4.2.1 on 2023-08-28 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
        ("userprofile", "0007_farmerprofile_reviewed_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="state",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="zip_code",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="address.address"
            ),
        ),
    ]
