# Generated by Django 4.2.1 on 2023-10-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_remove_userprofile_city_remove_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default='example@gmail.com', max_length=254, unique=True),
        ),
    ]
