# Generated by Django 4.2.1 on 2024-03-12 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_alter_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
