# Generated by Django 4.2.1 on 2023-09-04 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_rename_commodityname_commodity_commodity_name'),
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='commodity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commodity.commodity'),
        ),
    ]
