version: "3.9"

services:
  cubeseed:
    container_name: cubeseed-backend
    image: cubeseed
    build:
      dockerfile: docker/Dockerfile.local
      context: .
      args:
        - DJANGO_SETTINGS_MODULE=cubeseed.settings
    command: manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - migration

  migration:
    container_name: cubeseed-backend-migration
    image: cubeseed
    build:
      dockerfile: docker/Dockerfile.local
      context: .
      args:
        - DJANGO_SETTINGS_MODULE=cubeseed.settings
    command: manage.py migrate
    depends_on:
      - db

  db:
    container_name: cubeseed-backend-db
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=cubeseedsecret
      - POSTGRES_USER=cubeseed
      - POSTGRES_DB=cubeseedapis
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
