FROM python:3

ARG VERSION=v0.0.0.0.0.0
ARG DJANGO_SETTINGS_MODULE=cubeseed.settings
ENV VERSION=${VERSION}
ENV DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}

WORKDIR /app
COPY . /app
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENTRYPOINT ["python3"]

EXPOSE 8000
