# Generated by Django 4.2.1 on 2023-09-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity',
            old_name='commodityName',
            new_name='commodity_name',
        ),
    ]
