# Generated by Django 4.2.1 on 2023-09-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('course_link', models.URLField()),
                ('certificate_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
    ]
