# Generated by Django 4.2.1 on 2023-09-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_verification', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='certificate_code',
        ),
        migrations.AddField(
            model_name='course',
            name='verifications',
            field=models.ManyToManyField(blank=True, related_name='courses', to='course_verification.courseverification'),
        ),
    ]
