name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        options: ". -l 120 --check"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint --errors-only --disable=missing-docstring,too-many-ancestors --load-plugins pylint_django --load-plugins pylint_django.checkers.migrations --django-settings-module=cubeseed.settings $(git ls-files '*.py')
